create table users (userid int primary key, username varchar(20), password1 varchar(50),emailid varchar(50),gender varchar(10),city varchar(10),country varchar(10))
insert into users values(12,'mayuri','mayu123','mayu@gmail.com','female','Nagpur','India')
insert into users values(15,'vrushali','vrushali123','vrushali@gmail.com','female','Arvi','India')
insert into users values(14,'Sayali','sayali123','sayali@gmail.com','female','Bhandara','India')
insert into users values(19,'onkar','onkar123','onkar@gmail.com','male','Pune','India')
insert into users values(20,'ishan','ishan123','ishan@gmail.com','male','Pune','India')
insert into users values(25,'priya','priya123','priya@gmail.com','female','Akola','India')
insert into users values(11,'mrunal','mrunal123','mrunal@gmail.com','female','Nagpur','India')
insert into users values(9,'mayuri','mayu123','mayu@gmail.com','female','Nagpur','India')
insert into users values(6,'mayuri','mayu123','mayu@gmail.com','female','Nagpur','India')
insert into users values(8,'mayuri','mayu123','mayu@gmail.com','female','Nagpur','India')
